### ISSUE TITLE
jsdom causing startup fail on locally served

### ISSUE THREAD

**Issue by MattReimer** [mapbox/tilestream#143]
There seems to be a problem with `jsdom` 

Repro steps below. Anyone have any ideas?

```
matt$ npm install -S tilestream
matt$ cd node_modules/tilestream
matt$ ./index.js start

/some-path-blah-blah/TileStream-XSViewer/node_modules/tilestream/node_modules/bones/node_modules/jquery/node_modules/jsdom/lib/jsdom/browser/Window.js:39
  this._globalProxy = vm.runInContext("this", this);
                         ^
TypeError: needs a 'context' argument.
    at new Window (/some-path-blah-blah/TileStream-XSViewer/node_modules/tilestream/node_modules/bones/node_modules/jquery/node_modules/jsdom/lib/jsdom/browser/Window.js:39:26)
    at Object.exports.jsdom (/some-path-blah-blah/TileStream-XSViewer/node_modules/tilestream/node_modules/bones/node_modules/jquery/node_modules/jsdom/lib/jsdom.js:46:16)
    at create (/some-path-blah-blah/TileStream-XSViewer/node_modules/tilestream/node_modules/bones/node_modules/jquery/node-jquery.js:5:39)
    at /some-path-blah-blahTileStream-XSViewer/node_modules/tilestream/node_modules/bones/node_modules/jquery/node-jquery.js:9065:18
    at Object.<anonymous> (/some-path-blah-blahTileStream-XSViewer/node_modules/tilestream/node_modules/bones/node_modules/jquery/node-jquery.js:9067:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```

**Comment by springmeyer** [comment]
Stick with node v0.10.x and the version of jsdom should work.

**Comment by MattReimer** [comment]
Ah, ok. Might be an issue with my other stuff but I'll give it a go. Thanks!

**Comment by MattReimer** [comment]
I spoke too soon. I'm using node v0.10.32. Do I need to go even earlier?

**Comment by springmeyer** [comment]
try applying this patch (which hit tilemill recently): https://github.com/mapbox/tilemill/commit/a4e35a6c437da7499e4795e58d7c663bcb3424ca#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by MattReimer** [comment]
Ok, that seemed to work. Because the dependency is nested inside Tilestream -> bones -> jquery -> jsdom I had to manually copy it in there but now it seems to be working on my local system.

Thanks for the workaround.
